// TEMPORARY DATA

export let access = "admin";

export const employeesData= [
   {
    id: 1,
    employeeId: "EMP001",
    username: "Ali Raza",
    firstName: "Ali",
    lastName: "Raza",
    email: "ali.raza@hdcomputing",
    img: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 312 4567890",
    role: "Frontend Developer",
    department: "Development",
    project: "Employee Onboarding Portal",
    access: "user",
  },
  {
    id: 2,
    employeeId: "EMP002",
    username: "Ayesha Khan",
    firstName: "Ayesha",
    lastName: "Khan",
    email: "ayesha.khan@hdcomputing",
    img: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 333 9876543",
    role: "UI/UX Designer",
    department: "Design",
    project: "Salary Disbursement System",
    access: "user",
  },
  {
    id: 3,
    employeeId: "EMP003",
    username: "Bilal Ahmed",
    firstName: "Bilal",
    lastName: "Ahmed",
    email: "bilal.ahmed@hdcomputing",
    img: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 345 1234567",
    role: "Backend Developer",
    department: "Development",
    project: "Social Media Strategy 2025",
    access: "user",

  },
  {
    id: 4,
    employeeId: "EMP004",
    username: "Fatima Tariq",
    firstName: "Fatima",
    lastName: "Tariq",
    email: "fatima.tariq@hdcomputing",
    img: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 336 1112233",
    role: "HR Manager",
    department: "Human Resources",
    project: "Internal Helpdesk App",
    access: "user",

  },
  {
    id: 5,
    employeeId: "EMP005",
    username: "Zainab Shah",
    firstName: "Zainab",
    lastName: "Shah",
    email: "zainab.shah@hdcomputing",
    img: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 300 1122334",
    role: "Project Manager",
    department: "Management",
    project: "Vendor Management System",
    access: "user",

  },
  {
    id: 6,
    employeeId: "EMP006",
    username: "Usman Javed",
    firstName: "Usman",
    lastName: "Javed",
    email: "usman.javed@hdcomputing",
    img: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 321 9988776",
    role: "QA Engineer",
    department: "Quality Assurance",
    project: "Customer Feedback Loop",
    access: "user",

  },
  {
    id: 7,
    employeeId: "EMP007",
    username: "Mehwish Ali",
    firstName: "Mehwish",
    lastName: "Ali",
    email: "mehwish.ali@hdcomputing",
    img: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 313 2233445",
    role: "Content Writer",
    department: "Marketing",
    project: "Sales Dashboard Revamp",
    access: "user",

  },
  {
    id: 8,
    employeeId: "EMP008",
    username: "Hassan Nadeem",
    firstName: "Hassan",
    lastName: "Nadeem",
    email: "hassan.nadeem@hdcomputing",
    img: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 302 6677885",
    role: "DevOps Engineer",
    department: "IT Operations",
    project: "Facility Maintenance Tracker",
    access: "user",

  },
  {
    id: 9,
    employeeId: "EMP009",
    username: "Nimra Sheikh",
    firstName: "Nimra",
    lastName: "Sheikh",
    email: "nimra.sheikh@hdcomputing",
    img: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 308 3344556",
    role: "Business Analyst",
    department: "Product Management",
    project: "Facility Maintenance Tracker",
    access: "user",

  },
  {
    id: 10,
    employeeId: "EMP010",
    username: "Saad Ali",
    firstName: "Saad",
    lastName: "Ali",
    email: "saad.ali@hdcomputing",
    img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+92 310 5566778",
    role: "Full Stack Developer",
    department: "Development",
    project: "Facility Maintenance Tracker",
    access: "user",

  },
  {
  id: 11,
  employeeId: "EMP011",
  username: "Sara Malik",
  firstName: "Sara",
  lastName: "Malik",
  email: "sara.malik@hdcomputing",
  img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1200",
  phone: "+92 300 4455667",
  role: "Digital Marketer",
  department: "Marketing",
  project: "Facility Maintenance Tracker",
  access: "user",

},
{
  id: 12,
  employeeId: "EMP012",
  username: "Omar Farooq",
  firstName: "Omar",
  lastName: "Farooq",
  email: "omar.farooq@hdcomputing",
  img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1200",
  phone: "+92 301 7788990",
  role: "Mobile App Developer",
  department: "Development",
  project: "Facility Maintenance Tracker",
  access: "user",

},
{
  id: 13,
  employeeId: "EMP013",
  username: "Hira Yousuf",
  firstName: "Hira",
  lastName: "Yousuf",
  email: "hira.yousuf@hdcomputing",
  img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1200",
  phone: "+92 312 2233445",
  role: "Recruitment Specialist",
  department: "Human Resources",
  project: "Customer Feedback Loop",
  access: "user",

},
{
  id: 14,
  employeeId: "EMP014",
  username: "Junaid Shah",
  firstName: "Junaid",
  lastName: "Shah",
  email: "junaid.shah@hdcomputing",
  img: "https://images.pexels.com/photos/936117/pexels-photo-936117.jpeg?auto=compress&cs=tinysrgb&w=1200",
  phone: "+92 333 1122112",
  role: "IT Support Engineer",
  department: "IT Support",
  project: "Customer Feedback Loop",
  access: "user",

},
{
  id: 15,
  employeeId: "EMP015",
  username: "Aqsa Rehman",
  firstName: "Aqsa",
  lastName: "Rehman",
  email: "aqsa.rehman@hdcomputing",
  img: "https://images.pexels.com/photos/4587664/pexels-photo-4587664.jpeg?auto=compress&cs=tinysrgb&w=1200",
  phone: "+92 309 6677889",
  role: "Finance Executive",
  department: "Finance",
  project: "Facility Maintenance Tracker",
  access: "user",

}

];

export const announcementsData = [
  {
  id: 1,
  title: "Notice for Ali Khan's Performance Review",
  employee: "Ali Khan",
  date: "2025-01-01",
},
{
  id: 2,
  title: "Assignment Reminder for Sara Ahmed",
  employee: "Sara Ahmed",
  date: "2025-01-01",
},
{
  id: 3,
  title: "Meeting Schedule for Hamza Iqbal",
  employee: "Hamza Iqbal",
  date: "2025-01-01",
},
{
  id: 4,
  title: "Notice for Ayesha Siddiqui's Task Deadline",
  employee: "Ayesha Siddiqui",
  date: "2025-01-01",
},
{
  id: 5,
  title: "Training Session for Zainab Noor",
  employee: "Zainab Noor",
  date: "2025-01-01",
},
{
  id: 6,
  title: "Leave Request Update for Usman Tariq",
  employee: "Usman Tariq",
  date: "2025-01-01",
},
{
  id: 7,
  title: "Project Briefing for Fatima Khan",
  employee: "Fatima Khan",
  date: "2025-01-01",
},
{
  id: 8,
  title: "Attendance Notice for Bilal Qureshi",
  employee: "Bilal Qureshi",
  date: "2025-01-01",
},
{
  id: 9,
  title: "Appraisal Meeting with Mehwish Raza",
  employee: "Mehwish Raza",
  date: "2025-01-01",
},
{
  id: 10,
  title: "Compliance Reminder for Waleed Ansari",
  employee: "Waleed Ansari",
  date: "2025-01-01",
},

];

export const departmentsData = [
  {
    id: 1,
    departmentName: "Human Resources",
    totalEmployees: 12,
    floor: "1st Floor",
    supervisor: "Ayesha Khan",
  },
  {
    id: 2,
    departmentName: "Finance",
    totalEmployees: 10,
    floor: "2nd Floor",
    supervisor: "Bilal Ahmed",
  },
  {
    id: 3,
    departmentName: "IT Support",
    totalEmployees: 15,
    floor: "Basement",
    supervisor: "Zain Ali",
  },
  {
    id: 4,
    departmentName: "Marketing",
    totalEmployees: 8,
    floor: "3rd Floor",
    supervisor: "Maham Raza",
  },
  {
    id: 5,
    departmentName: "Procurement",
    totalEmployees: 7,
    floor: "2nd Floor",
    supervisor: "Farhan Siddiqui",
  },
  {
    id: 6,
    departmentName: "Sales",
    totalEmployees: 14,
    floor: "3rd Floor",
    supervisor: "Nida Farooq",
  },
  {
    id: 7,
    departmentName: "Customer Support",
    totalEmployees: 11,
    floor: "1st Floor",
    supervisor: "Usman Tariq",
  },
  {
    id: 8,
    departmentName: "Legal Affairs",
    totalEmployees: 5,
    floor: "Top Floor",
    supervisor: "Sadia Qureshi",
  },
  {
    id: 9,
    departmentName: "Compliance",
    totalEmployees: 6,
    floor: "Basement",
    supervisor: "Imran Saeed",
  },
  {
    id: 10,
    departmentName: "Admin",
    totalEmployees: 9,
    floor: "Ground Floor",
    supervisor: "Mehwish Javed",
  },
];

export const projectsData = [
  {
    id: 1,
    projectName: "Employee Onboarding Portal",
    department: "Human Resources",
    lead: "Ayesha Khan",
  },
  {
    id: 2,
    projectName: "Salary Disbursement System",
    department: "Finance",
    lead: "Bilal Ahmed",
  },
  {
    id: 3,
    projectName: "Internal Helpdesk App",
    department: "IT Support",
    lead: "Zain Ali",
  },
  {
    id: 4,
    projectName: "Social Media Strategy 2025",
    department: "Marketing",
    lead: "Maham Raza",
  },
  {
    id: 5,
    projectName: "Vendor Management System",
    department: "Procurement",
    lead: "Farhan Siddiqui",
  },
  {
    id: 6,
    projectName: "Sales Dashboard Revamp",
    department: "Sales",
    lead: "Nida Farooq",
  },
  {
    id: 7,
    projectName: "Customer Feedback Loop",
    department: "Customer Support",
    lead: "Usman Tariq",
  },
  {
    id: 8,
    projectName: "Contract Review Automation",
    department: "Legal Affairs",
    lead: "Sadia Qureshi",
  },
  {
    id: 9,
    projectName: "Data Security Audit Q4",
    department: "Compliance",
    lead: "Imran Saeed",
  },
  {
    id: 10,
    projectName: "Facility Maintenance Tracker",
    department: "Admin",
    lead: "Mehwish Javed",
  },
];

// trainings
// performance

export const assignmentsData = [
  {
    id: 1,
    task: "Prepare Monthly HR Report",
    department: "Human Resources",
    assignedTo: "Ayesha Khan",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    task: "Process Payroll for December",
    department: "Finance",
    assignedTo: "Bilal Ahmed",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    task: "Install Antivirus on All Systems",
    department: "IT Support",
    assignedTo: "Zain Ali",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    task: "Launch New Marketing Campaign",
    department: "Marketing",
    assignedTo: "Maham Raza",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    task: "Order Office Supplies",
    department: "Procurement",
    assignedTo: "Farhan Siddiqui",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    task: "Update Sales Performance Sheet",
    department: "Sales",
    assignedTo: "Nida Farooq",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    task: "Compile Customer Feedback Report",
    department: "Customer Support",
    assignedTo: "Usman Tariq",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    task: "Review Legal Contract Draft",
    department: "Legal Affairs",
    assignedTo: "Sadia Qureshi",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    task: "Conduct Security Compliance Check",
    department: "Compliance",
    assignedTo: "Imran Saeed",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    task: "Schedule Facility Maintenance",
    department: "Admin",
    assignedTo: "Mehwish Javed",
    dueDate: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Team Meeting",
    allDay: false,
    start: new Date(2025, 7, 12, 8, 0),
    end: new Date(2025, 7, 12, 8, 45),
  },
  {
    title: "Client Presentation",
    allDay: false,
    start: new Date(2025, 7, 12, 9, 0),
    end: new Date(2025, 7, 12, 9, 45),
  },
  {
    title: "Code Review Session",
    allDay: false,
    start: new Date(2025, 7, 12, 10, 0),
    end: new Date(2025, 7, 12, 10, 45),
  },
  {
    title: "Project Planning",
    allDay: false,
    start: new Date(2025, 7, 12, 11, 0),
    end: new Date(2025, 7, 12, 11, 45),
  },
  {
    title: "Product Demo",
    allDay: false,
    start: new Date(2025, 7, 12, 13, 0),
    end: new Date(2025, 7, 12, 13, 45),
  },
  {
    title: "Weekly Review",
    allDay: false,
    start: new Date(2025, 7, 12, 14, 0),
    end: new Date(2025, 7, 12, 14, 45),
  },
  {
    title: "Client Feedback Session",
    allDay: false,
    start: new Date(2025, 7, 13, 9, 0),
    end: new Date(2025, 7, 13, 9, 45),
  },
  {
    title: "Design Review",
    allDay: false,
    start: new Date(2025, 7, 13, 10, 0),
    end: new Date(2025, 7, 13, 10, 45),
  },
  {
    title: "Sprint Planning",
    allDay: false,
    start: new Date(2025, 7, 13, 11, 0),
    end: new Date(2025, 7, 13, 11, 45),
  },
  {
    title: "Department Meeting",
    allDay: false,
    start: new Date(2025, 7, 13, 14, 0),
    end: new Date(2025, 7, 13, 14, 45),
  },
  {
    title: "Feature Deployment",
    allDay: false,
    start: new Date(2025, 7, 14, 8, 0),
    end: new Date(2025, 7, 14, 8, 45),
  },
  {
    title: "System Testing",
    allDay: false,
    start: new Date(2025, 7, 14, 10, 0),
    end: new Date(2025, 7, 14, 10, 45),
  },
  {
    title: "API Integration",
    allDay: false,
    start: new Date(2025, 7, 14, 13, 0),
    end: new Date(2025, 7, 14, 13, 45),
  },
  {
    title: "HR Check-In",
    allDay: false,
    start: new Date(2025, 7, 14, 14, 0),
    end: new Date(2025, 7, 14, 14, 45),
  },
  {
    title: "Retrospective Meeting",
    allDay: false,
    start: new Date(2025, 7, 15, 9, 0),
    end: new Date(2025, 7, 15, 9, 45),
  },
  {
    title: "Performance Review",
    allDay: false,
    start: new Date(2025, 7, 15, 10, 0),
    end: new Date(2025, 7, 15, 10, 45),
  },
  {
    title: "Tech Sync",
    allDay: false,
    start: new Date(2025, 7, 15, 11, 0),
    end: new Date(2025, 7, 15, 11, 45),
  },
  {
    title: "Team Building Activity",
    allDay: false,
    start: new Date(2025, 7, 15, 14, 0),
    end: new Date(2025, 7, 15, 14, 45),
  },
  {
    title: "Database Backup",
    allDay: false,
    start: new Date(2025, 7, 16, 8, 0),
    end: new Date(2025, 7, 16, 8, 45),
  },
  {
    title: "UX Review",
    allDay: false,
    start: new Date(2025, 7, 16, 9, 0),
    end: new Date(2025, 7, 16, 9, 45),
  },
  {
    title: "DevOps Sync",
    allDay: false,
    start: new Date(2025, 7, 16, 11, 0),
    end: new Date(2025, 7, 16, 11, 45),
  },
  {
    title: "Team Feedback",
    allDay: false,
    start: new Date(2025, 7, 16, 13, 0),
    end: new Date(2025, 7, 16, 13, 45),
  },
  {
    title: "Manager 1-on-1",
    allDay: false,
    start: new Date(2025, 7, 16, 14, 0),
    end: new Date(2025, 7, 16, 14, 45),
  },
];

