import { Inter } from "next/font/google";
import "./globals.scss";
import "/styles/theme.scss";
import Script from "next/script";
import { Toaster } from "react-hot-toast";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HR Management",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
       <head>
        {/* Add Lordicon script */}
        <link href= "https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <Script src="https://cdn.lordicon.com/lordicon.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"/>
      </head>
      <body >
          <main>
            <Toaster position="top-right" />
            {children}
          </main>
      </body>
    </html>
  );
}
export default RootLayout;
